# ASP.NET Core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) ./src/
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: DotNetCoreCLI@3
  inputs:
    command: 'test'
    projects: './src/Rhyze.Tests/Rhyze.Tests.csproj'
    testRunTitle: 'Running Tests Project'
