version: '3.4'

services:
  sql:
    image: mcr.microsoft.com/mssql/server
    container_name: rhyze_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=B43tn4t!0n
    ports:
      - "1433:1433"
    volumes:
      - ./vol/sql:/var/opt/mssql/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: rhyze_azurite
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./vol/azurite:/data
